### ISSUE TITLE
Plan for LEAP

### ISSUE THREAD

**Issue by GZHoffie** [GZHoffie/approximate-string-matching#1]
# Timeline
Milestone 1: June 14th
Milestone 2: July 17th

# Deliverables

Milestone 1:

- [ ] Code to combine LEAP with mappers
- [ ] Benchmark results with mappers and other approximate-string-matching algorithms
- [ ] Fix errors in the paper and publish the paper

Milestone 2:

- [x] A greedy algorithm that tries to solve the approximate-string-matching problem
- [x] Benchmark results
- [ ] A paper that describes the idea

# TO-DO

Approximately one task per weak

- [ ] Explore combination with mappers (5.24)
   - Try to combine LEAP to mappers such as BWA-MEM (Li, 2013) and Bowtie2 (Langmead and Salzberg, 2012)
   - Find a way to calculate and compare **recall** of the result to ensure accuracy
- [ ] Benchmark results (5.31)
   - Run LEAP and other approximate string matching algorithm **on the same machine** with real/simulated data
   - Explore the performance in affine gap case
   - Compare the results
- [ ] Edit paper of LEAP (6.7)
   - Fix errors in pseudocode, add benchmark
- [x] Propose a greedy algorithm (6.21)
   - Try to find a scoring system to ensure optimality
   - Try to find a way to prove this optimality
- [x] Implementation of the greedy algorithm (6.28)
   - Maybe a draft using python
   - Implement using C++ for full bit parallelism
- [ ] Benchmark results (7.5)
   - Run the algorithm and compare the results with other algorithms
   - Try to combine it with mappers.
- [ ] Produce draft of a paper for the algorithm (7.12)
